# AAI614: Data Science & its Applications

*Notebook 2.5: Practice with Parquet and File Types*

<a href="https://colab.research.google.com/github/harmanani/AAI614/blob/main/Week%202/Notebook2.5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import time
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

In [7]:
class Timer:
    def __enter__(self):
        self.start = time.perf_counter()
        return self

    def __exit__(self, *args):
        self.end = time.perf_counter()
        self.interval = self.end - self.start

##### Read the Parqeut file and time it

In [8]:
with Timer() as t_pd:
    df = pd.read_parquet('https://raw.githubusercontent.com/harmanani/AAI614/main/Week%202/niaaa-report.parquet')
print(t_pd.interval)

0.03940831600016281

In [11]:
df.head()

     State  Year  Beer  Wine  Spirits
0  Alabama  1977  0.99  0.13     0.84
1  Alabama  1978  0.98  0.12     0.88
2  Alabama  1979  0.98  0.12     0.84
3  Alabama  1980  0.96  0.16     0.74
4  Alabama  1981  1.00  0.19     0.73

#### Read the CSV file and time it

In [9]:
with Timer() as t_pd:
    df = pd.read_csv('https://raw.githubusercontent.com/harmanani/AAI614/main/Week%202/niaaa-report.csv')
print(t_pd.interval)

0.04389820799997324

In [12]:
df.head()

     State  Year  Beer  Wine  Spirits
0  Alabama  1977  0.99  0.13     0.84
1  Alabama  1978  0.98  0.12     0.88
2  Alabama  1979  0.98  0.12     0.84
3  Alabama  1980  0.96  0.16     0.74
4  Alabama  1981  1.00  0.19     0.73

#### Read the ZIP file and time it

In [10]:
import zipfile
with Timer() as t_pd:
    df = pd.read_csv('https://raw.githubusercontent.com/harmanani/AAI614/main/Week%202/niaaa-report.zip', compression="zip")
print(t_pd.interval)

0.036878826000020126

In [13]:
df.head()

     State  Year  Beer  Wine  Spirits
0  Alabama  1977  0.99  0.13     0.84
1  Alabama  1978  0.98  0.12     0.88
2  Alabama  1979  0.98  0.12     0.84
3  Alabama  1980  0.96  0.16     0.74
4  Alabama  1981  1.00  0.19     0.73